"""
GearCargo - Push Notifications Routes
"""

import base64
import re
from datetime import datetime, timezone
from flask import Blueprint, request, jsonify, current_app
from pywebpush import webpush, WebPushException
import json
import requests.exceptions

from app import db
from app.models import PushSubscription, NotificationLog
from app.routes.auth import token_required

push_bp = Blueprint('push', __name__)


def _vapid_pubkey_to_base64url(key_str: str):
    """
    Normalize a VAPID public key to URL-safe base64 (no padding).

    The browser's PushManager.subscribe() requires the 65-byte uncompressed
    P-256 key (04 || X || Y) encoded as URL-safe base64.  Handles three input
    formats:
      - Already the correct 65-byte raw point in base64url
      - DER-encoded SubjectPublicKeyInfo (91 bytes, starts with MFkw) —
        generated by py_vapid / openssl; the raw point is the last 65 bytes
      - Raw hex (legacy setup.sh fallback)

    Returns the normalised string, or None if the key is unusable.
    """
    if not key_str:
        return None
    s = key_str.strip()

    # Detect raw hex (only [0-9a-fA-F], even length) and convert to base64url.
    if re.fullmatch(r'[0-9a-fA-F]+', s) and len(s) % 2 == 0:
        s = base64.urlsafe_b64encode(bytes.fromhex(s)).rstrip(b'=').decode('ascii')

    try:
        padding = '=' * ((4 - len(s) % 4) % 4)
        raw = base64.urlsafe_b64decode(s + padding)

        # Already the correct raw uncompressed P-256 point.
        if len(raw) == 65 and raw[0] == 0x04:
            return s

        # DER SubjectPublicKeyInfo (91 bytes for P-256). The uncompressed EC
        # point (65 bytes, starting with 0x04) lives at the very end after the
        # BIT STRING header (03 42 00).  Extract and re-encode it.
        if len(raw) == 91:
            # The P-256 SPKI DER prefix ends with 03 42 00 04 — find the 0x04
            # start byte robustly by looking for the BIT STRING wrapper.
            BIT_STRING_HDR = bytes([0x03, 0x42, 0x00, 0x04])
            idx = raw.find(BIT_STRING_HDR)
            if idx != -1:
                point = raw[idx + 3:]  # skip 03 42 00, keep 04||X||Y
                if len(point) == 65 and point[0] == 0x04:
                    return base64.urlsafe_b64encode(point).rstrip(b'=').decode('ascii')
    except Exception:
        pass
    return None


def _vapid_privkey_to_pem(key_str: str) -> str:
    """
    Normalize a VAPID private key to PEM format accepted by pywebpush.

    Handles:
      - PEM string (returned as-is)
      - DER-encoded SEC1 ECPrivateKey in base64url (e.g. from py_vapid's
        Vapid.serialize() — starts with 'MHc') — wrapped in PEM block
      - Raw 32-byte scalar in base64url — not currently converted (returned
        as-is for py_vapid's own from_string() to handle)
    """
    if not key_str:
        return key_str
    s = key_str.strip()
    if s.startswith('-----'):
        return s  # already PEM
    try:
        padding = '=' * ((4 - len(s) % 4) % 4)
        raw = base64.urlsafe_b64decode(s + padding)
        if len(raw) > 32 and raw[0] == 0x30:
            # DER — convert to standard base64, wrap in PEM
            b64 = base64.b64encode(raw).decode('ascii')
            lines = [b64[i:i+64] for i in range(0, len(b64), 64)]
            return '-----BEGIN EC PRIVATE KEY-----\n' + '\n'.join(lines) + '\n-----END EC PRIVATE KEY-----'
    except Exception:
        pass
    return s


@push_bp.route('/vapid-key', methods=['GET'])
def get_vapid_key():
    """Get VAPID public key for push subscriptions."""
    raw_key = current_app.config.get('VAPID_PUBLIC_KEY', '')
    normalized = _vapid_pubkey_to_base64url(raw_key)

    if not normalized:
        return jsonify({'error': 'Push notifications not configured'}), 503

    return jsonify({'public_key': normalized})


@push_bp.route('/subscribe', methods=['POST'])
@token_required
def subscribe(current_user):
    """Subscribe to push notifications."""
    data = request.get_json()
    
    subscription = data.get('subscription')
    if not subscription:
        return jsonify({'error': 'Subscription data required'}), 400
    
    endpoint = subscription.get('endpoint')
    keys = subscription.get('keys', {})
    
    if not endpoint or not keys.get('p256dh') or not keys.get('auth'):
        return jsonify({'error': 'Invalid subscription data'}), 400
    
    # Check if subscription already exists
    existing = PushSubscription.query.filter_by(endpoint=endpoint).first()
    
    if existing:
        if existing.user_id == current_user.id:
            # Legitimate re-registration from the same user — refresh keys and device info.
            existing.p256dh_key = keys['p256dh']
            existing.auth_key = keys['auth']
            existing.active = True
            existing.device_name = data.get('device_name')
            existing.device_type = data.get('device_type')
            existing.browser = data.get('browser')
            existing.os = data.get('os')
            db.session.commit()

            return jsonify({
                'message': 'Subscription updated',
                'subscription': existing.to_dict()
            })
        else:
            # Endpoint already belongs to a different user — this is either a stale record
            # from a shared device whose previous owner did not unsubscribe cleanly, or a
            # deliberate attempt to hijack another user's push endpoint.
            # In both cases: evict the stale record so the current user gets a clean
            # registration below. Never silently transfer ownership across users.
            current_app.logger.warning(
                '[Security] Push endpoint re-registration: evicting stale record '
                'for user_id=%s, new owner user_id=%s',
                existing.user_id, current_user.id
            )
            db.session.delete(existing)
            db.session.flush()   # enforce deletion before the INSERT below
    
    # Create new subscription
    push_sub = PushSubscription(
        user_id=current_user.id,
        endpoint=endpoint,
        p256dh_key=keys['p256dh'],
        auth_key=keys['auth'],
        device_name=data.get('device_name'),
        device_type=data.get('device_type'),
        browser=data.get('browser'),
        os=data.get('os'),
    )
    
    db.session.add(push_sub)
    db.session.commit()
    
    return jsonify({
        'message': 'Successfully subscribed to push notifications',
        'subscription': push_sub.to_dict()
    }), 201


@push_bp.route('/unsubscribe', methods=['POST'])
@token_required
def unsubscribe(current_user):
    """Unsubscribe from push notifications."""
    data = request.get_json()
    endpoint = data.get('endpoint')
    
    if not endpoint:
        return jsonify({'error': 'Endpoint required'}), 400
    
    subscription = PushSubscription.query.filter_by(
        user_id=current_user.id,
        endpoint=endpoint
    ).first()
    
    if not subscription:
        return jsonify({'error': 'Subscription not found'}), 404
    
    db.session.delete(subscription)
    db.session.commit()
    
    return jsonify({'message': 'Successfully unsubscribed'})


@push_bp.route('/subscriptions', methods=['GET'])
@token_required
def get_subscriptions(current_user):
    """Get user's push subscriptions."""
    subscriptions = PushSubscription.query.filter_by(
        user_id=current_user.id,
        active=True
    ).all()
    
    return jsonify({
        'subscriptions': [s.to_dict() for s in subscriptions]
    })


@push_bp.route('/subscriptions/<int:sub_id>', methods=['DELETE'])
@token_required
def delete_subscription(current_user, sub_id):
    """Delete a specific push subscription."""
    subscription = PushSubscription.query.filter_by(
        id=sub_id,
        user_id=current_user.id
    ).first()
    
    if not subscription:
        return jsonify({'error': 'Subscription not found'}), 404
    
    db.session.delete(subscription)
    db.session.commit()
    
    return jsonify({'message': 'Subscription deleted'})


@push_bp.route('/test', methods=['POST'])
@token_required
def test_notification(current_user):
    """Send a test push notification."""
    data = request.get_json(silent=True) or {}
    
    subscriptions = PushSubscription.query.filter_by(
        user_id=current_user.id,
        active=True
    ).all()
    
    if not subscriptions:
        return jsonify({'error': 'No active push subscriptions found. Please enable notifications first.'}), 422
    
    vapid_private = current_app.config.get('VAPID_PRIVATE_KEY')
    vapid_subject = current_app.config.get('VAPID_SUBJECT', 'mailto:admin@gearcargo.local')

    if not vapid_private:
        return jsonify({'error': 'Push notifications not configured'}), 503

    notification_data = {
        'title': data.get('title', 'GearCargo Test'),
        'body': data.get('body', 'This is a test notification'),
        'icon': '/icons/logo-192.png',
        'badge': '/icons/badge-72.png',
        'tag': 'test',
        'data': {
            'url': '/',
            'type': 'test'
        }
    }

    sent = 0
    failed = 0

    for sub in subscriptions:
        try:
            webpush(
                subscription_info=sub.get_subscription_info(),
                data=json.dumps(notification_data),
                vapid_private_key=_vapid_privkey_to_pem(vapid_private),
                vapid_claims={
                    'sub': vapid_subject
                },
                timeout=10,
            )
            sub.mark_used()
            sent += 1

        except WebPushException as e:
            current_app.logger.warning(
                '[Push] WebPushException for sub %s: %s (HTTP %s)',
                sub.id, e,
                e.response.status_code if e.response else 'N/A',
            )
            sub.mark_error(str(e))
            failed += 1

            # Remove subscription if the push service says it's gone
            if e.response and e.response.status_code in [404, 410]:
                db.session.delete(sub)

        except (requests.exceptions.RequestException, Exception) as e:
            current_app.logger.error(
                '[Push] Unexpected error sending to sub %s: %s: %s',
                sub.id, type(e).__name__, e,
            )
            sub.mark_error(f'{type(e).__name__}: {e}')
            failed += 1
    
    db.session.commit()
    
    return jsonify({
        'message': 'Test notification sent',
        'sent': sent,
        'failed': failed
    })


@push_bp.route('/history', methods=['GET'])
@token_required
def get_notification_history(current_user):
    """Get notification history."""
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 20, type=int)
    
    logs = NotificationLog.query.filter_by(
        user_id=current_user.id
    ).order_by(NotificationLog.created_at.desc()).paginate(
        page=page, per_page=per_page, error_out=False
    )
    
    return jsonify({
        'notifications': [n.to_dict() for n in logs.items],
        'total': logs.total,
        'pages': logs.pages,
        'current_page': page,
    })


def send_push_to_user(user_id, title, body, data=None, tag=None):
    """Send push notification to all user's subscriptions."""
    from flask import current_app
    
    subscriptions = PushSubscription.query.filter_by(
        user_id=user_id,
        active=True
    ).all()
    
    if not subscriptions:
        return 0
    
    vapid_private = current_app.config.get('VAPID_PRIVATE_KEY')
    vapid_subject = current_app.config.get('VAPID_SUBJECT', 'mailto:admin@gearcargo.local')

    if not vapid_private:
        return 0

    notification_data = {
        'title': title,
        'body': body,
        'icon': '/icons/logo-192.png',
        'badge': '/icons/badge-72.png',
        'tag': tag or 'gearcargo',
        'data': data or {}
    }

    sent = 0

    for sub in subscriptions:
        try:
            webpush(
                subscription_info=sub.get_subscription_info(),
                data=json.dumps(notification_data),
                vapid_private_key=_vapid_privkey_to_pem(vapid_private),
                vapid_claims={
                    'sub': vapid_subject
                },
                timeout=10,
            )
            sub.mark_used()
            sent += 1

            # Log notification
            log = NotificationLog(
                user_id=user_id,
                subscription_id=sub.id,
                notification_type=data.get('type', 'general') if data else 'general',
                title=title,
                body=body,
                data=data,
                channel='push',
                status='sent',
                sent_at=datetime.now(timezone.utc)
            )
            db.session.add(log)

        except WebPushException as e:
            current_app.logger.warning(
                '[Push] WebPushException for sub %s user %s: %s (HTTP %s)',
                sub.id, user_id, e,
                e.response.status_code if e.response else 'N/A',
            )
            sub.mark_error(str(e))
            if e.response and e.response.status_code in [404, 410]:
                db.session.delete(sub)

        except (requests.exceptions.RequestException, Exception) as e:
            current_app.logger.error(
                '[Push] Unexpected error sending to sub %s user %s: %s: %s',
                sub.id, user_id, type(e).__name__, e,
            )
            sub.mark_error(f'{type(e).__name__}: {e}')

    db.session.commit()
    return sent
