/* eslint-disable no-restricted-globals */

// CACHE VERSION - increment to force update
const CACHE_VERSION = 'v2.0.1'

// Dev-only logger — compiled to a no-op in production builds by Vite
// so no internal details leak to the browser console in production.
const log = import.meta.env.DEV ? console.log.bind(console) : () => {}

log('Service Worker Version:', CACHE_VERSION)

import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL, matchPrecache } from 'workbox-precaching'
import { registerRoute, NavigationRoute, setCatchHandler } from 'workbox-routing'
import { CacheFirst, NetworkFirst, StaleWhileRevalidate, NetworkOnly } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'
import { BackgroundSyncPlugin } from 'workbox-background-sync'
import { FLUSH_QUEUE_SYNC_TAG, REMINDER_REFRESH_TAG } from './utils/syncTags'

// ============================================================
// BACKGROUND SYNC CONFIGURATION
// ============================================================

// Create a background sync plugin for API mutations (POST, PUT, DELETE)
const bgSyncPlugin = new BackgroundSyncPlugin('gearcargo-sync-queue', {
  maxRetentionTime: 24 * 60, // Retry for up to 24 hours (in minutes)
  onSync: async ({ queue }) => {
    let entry
    while ((entry = await queue.shiftRequest())) {
      try {
        await fetch(entry.request.clone())
        
        // Notify the app that sync succeeded
        const clients = await self.clients.matchAll()
        for (const client of clients) {
          client.postMessage({
            type: 'SYNC_SUCCESS',
            url: entry.request.url,
            method: entry.request.method,
          })
        }
        
        log('Background sync successful:', entry.request.url)
      } catch (error) {
        console.error('Background sync failed, re-queuing:', error)
        // Put the entry back in the queue and re-throw to signal failure
        await queue.unshiftRequest(entry)
        throw error
      }
    }
    
    // Notify app that all syncs are complete
    const clients = await self.clients.matchAll()
    for (const client of clients) {
      client.postMessage({
        type: 'SYNC_COMPLETE',
        message: 'All offline changes have been synced',
      })
    }
  },
})

// ============================================================
// PRECACHING
// ============================================================

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST)

// Clean up old caches
cleanupOutdatedCaches()

// SPA navigation fallback - serve index.html for all navigation requests
const navigationHandler = createHandlerBoundToURL('/index.html')
const navigationRoute = new NavigationRoute(navigationHandler, {
  // Exclude API routes and the offline fallback page from SPA navigation handling.
  // offline.html must be reachable directly so setCatchHandler can return it.
  denylist: [/^\/api/, /^\/offline\.html$/],
})
registerRoute(navigationRoute)

// Take control of clients immediately after activation
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim())
})

// Cache Google Fonts stylesheets
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
)

// Cache Google Fonts webfonts
registerRoute(
  ({ url }) => url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
        maxEntries: 30,
      }),
    ],
  })
)

// Cache Material Icons
registerRoute(
  ({ url }) => url.href.includes('material-icons') || url.href.includes('Material+Icons'),
  new CacheFirst({
    cacheName: 'material-icons',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365,
        maxEntries: 10,
      }),
    ],
  })
)

// Cache images
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
    ],
  })
)

// Endpoints whose GET responses must NEVER be cached on disk:
// - identity/session (stale identity is dangerous; the app caches the user in
//   Dexie instead), admin data, CSRF tokens, backup downloads (large/sensitive
//   blobs), and push subscription info. These pass through to the network and
//   simply fail when offline, which is correct for auth/admin surfaces.
const API_CACHE_DENYLIST = ['/api/auth/', '/api/admin/', '/api/csrf-token', '/api/backup/', '/api/push/']

function isCacheableApiGet(url, request) {
  if (request.method !== 'GET' || !url.pathname.startsWith('/api/')) return false
  return !API_CACHE_DENYLIST.some((prefix) => url.pathname.startsWith(prefix))
}

// Cache data-read API GETs with NetworkFirst (network wins; falls back to the
// last-good cached copy when offline). The `api-cache` is purged on login AND
// logout (see clearApiCache / CLEAR_API_CACHE) so one user's data is never
// served to another account or after sign-out on a shared device.
registerRoute(
  ({ url, request }) => isCacheableApiGet(url, request),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24, // 24 hours
      }),
    ],
    networkTimeoutSeconds: 10,
  })
)

// ============================================================
// BACKGROUND SYNC FOR API MUTATIONS (POST, PUT, DELETE)
// Queue failed requests when offline and retry when back online
// ============================================================

// §14.7 — the AI vehicle chat is request/response and must NEVER be queued or
// replayed offline: a replayed question would run remote inference later with no
// UI to show the answer (wasted + confusing). Match it FIRST as plain NetworkOnly
// (no background sync) so it fails fast offline instead of being queued.
registerRoute(
  ({ url, request }) => request.method === 'POST' && /^\/api\/vehicles\/\d+\/chat$/.test(url.pathname),
  new NetworkOnly(),
  'POST'
)

// Handle POST requests with background sync
registerRoute(
  ({ url, request }) => url.pathname.startsWith('/api/') && request.method === 'POST',
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'POST'
)

// Handle PUT requests with background sync
registerRoute(
  ({ url, request }) => url.pathname.startsWith('/api/') && request.method === 'PUT',
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'PUT'
)

// Handle PATCH requests with background sync
registerRoute(
  ({ url, request }) => url.pathname.startsWith('/api/') && request.method === 'PATCH',
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'PATCH'
)

// Handle DELETE requests with background sync
registerRoute(
  ({ url, request }) => url.pathname.startsWith('/api/') && request.method === 'DELETE',
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'DELETE'
)

// Cache static assets
registerRoute(
  ({ request }) =>
    request.destination === 'script' ||
    request.destination === 'style',
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
  })
)

// ============================================================
// WEB SHARE TARGET — receive a shared receipt image
// ============================================================
// The manifest share_target posts the shared file here (multipart/form-data).
// We stash it in a dedicated cache under a fixed key and 303-redirect into the
// SPA; the /share-target React route then reads it, uploads it to the chosen
// vehicle and runs OCR. The file stays on-device and the page deletes it right
// after reading (privacy — no shared receipt lingers in storage).
const SHARE_TARGET_CACHE = 'share-target-cache'
const SHARED_FILE_KEY = '/__shared_receipt'

registerRoute(
  ({ url, request }) => url.pathname === '/share-target' && request.method === 'POST',
  async ({ request }) => {
    try {
      const formData = await request.formData()
      const file = formData.get('receipt')
      if (file && typeof file !== 'string' && file.size > 0) {
        const cache = await caches.open(SHARE_TARGET_CACHE)
        const headers = new Headers({
          'content-type': file.type || 'application/octet-stream',
          'x-shared-filename': encodeURIComponent(file.name || 'receipt.jpg'),
        })
        await cache.put(SHARED_FILE_KEY, new Response(file, { headers }))
      }
    } catch (error) {
      log('Share target handling failed:', error)
    }
    // Redirect to a GET navigation so the SPA fallback serves the app shell.
    return Response.redirect('/share-target', 303)
  },
  'POST'
)

// ============================================================
// OFFLINE FALLBACK
// ============================================================
// I16: offline.html is included in self.__WB_MANIFEST via globPatterns (*.html).
// Workbox assigns it a content-hash revision; when the file changes the hash
// changes, the new SW downloads and caches the updated page, and
// cleanupOutdatedCaches() removes the stale copy — automatic versioning.
//
// setCatchHandler fires only when ALL other routes fail (e.g. network down
// while offline). matchPrecache resolves the versioned cache key automatically.
setCatchHandler(async ({ request }) => {
  if (request.destination === 'document') {
    const cached = await matchPrecache('/offline.html')
    return cached || Response.error()
  }
  return Response.error()
})

// ============================================================
// MESSAGE HANDLING
// ============================================================

// Listen for messages from the main thread
self.addEventListener('message', async (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }

  // Purge cached API responses (called on login/logout so authenticated data
  // is never served across accounts or after sign-out on a shared device).
  if (event.data && event.data.type === 'CLEAR_API_CACHE') {
    event.waitUntil(caches.delete('api-cache'))
  }

  // Handle request to get pending sync count
  if (event.data && event.data.type === 'GET_PENDING_SYNC_COUNT') {
    try {
      const db = await openSyncDatabase()
      const tx = db.transaction('requests', 'readonly')
      const store = tx.objectStore('requests')
      const count = await new Promise((resolve, reject) => {
        const request = store.count()
        request.onsuccess = () => resolve(request.result)
        request.onerror = () => reject(request.error)
      })
      
      event.ports[0].postMessage({ count })
    } catch (error) {
      event.ports[0].postMessage({ count: 0, error: error.message })
    }
  }
  
  // Force sync attempt
  if (event.data && event.data.type === 'FORCE_SYNC') {
    try {
      await self.registration.sync.register('workbox-background-sync:gearcargo-sync-queue')
      event.ports[0]?.postMessage({ success: true })
    } catch (error) {
      console.error('Manual sync registration failed:', error)
      event.ports[0]?.postMessage({ success: false, error: error.message })
    }
  }
})

// Helper to open the Workbox background sync IndexedDB
function openSyncDatabase() {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open('workbox-background-sync', 3)
    request.onerror = () => reject(request.error)
    request.onsuccess = () => resolve(request.result)
  })
}

// ============================================================
// PUSH NOTIFICATIONS
// ============================================================

// Handle push notifications
self.addEventListener('push', (event) => {
  if (!event.data) return
  
  const data = event.data.json()
  
  const options = {
    body: data.body || 'New notification',
    icon: '/icons/logo-192.png',
    badge: '/icons/logo-72.png',
    vibrate: [100, 50, 100],
    data: {
      url: data.url || '/',
    },
    actions: data.actions || [],
    tag: data.tag || 'gearcargo-notification',
    renotify: true,
  }
  
  event.waitUntil(
    self.registration.showNotification(data.title || 'GearCargo', options)
  )
})

// Handle notification click
self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  
  const urlToOpen = event.notification.data?.url || '/'
  
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        // Check if there's already a window open
        for (const client of clientList) {
          if (client.url === urlToOpen && 'focus' in client) {
            return client.focus()
          }
        }
        // Open a new window
        if (self.clients.openWindow) {
          return self.clients.openWindow(urlToOpen)
        }
      })
  )
})

// ============================================================
// PUSH SUBSCRIPTION LIFECYCLE
// ============================================================

// Decode a base64url VAPID key into the Uint8Array applicationServerKey expects.
function urlBase64ToUint8Array(base64String) {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4)
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/')
  const rawData = atob(base64)
  const outputArray = new Uint8Array(rawData.length)
  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i)
  }
  return outputArray
}

// The browser rotates/expires push subscriptions periodically. Without handling
// this event the user silently stops receiving notifications. Re-subscribe with
// the current VAPID key and re-register with the server (the httpOnly auth
// cookie rides along automatically; if the session is gone the POST 401s and we
// simply give up until the user opens the app again).
async function resubscribeToPush() {
  try {
    const response = await fetch('/api/push/vapid-key', { credentials: 'include' })
    if (!response.ok) return
    const { public_key: vapidPublicKey } = await response.json()
    if (!vapidPublicKey) return

    const newSubscription = await self.registration.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: urlBase64ToUint8Array(vapidPublicKey),
    })

    // Best-effort device hints (no PII beyond the UA string the server already sees).
    const ua = self.navigator?.userAgent || ''
    let deviceType = 'desktop'
    if (/Mobile|Android|iPhone|iPad/.test(ua)) deviceType = /iPad/.test(ua) ? 'tablet' : 'mobile'

    await fetch('/api/push/subscribe', {
      method: 'POST',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        subscription: newSubscription.toJSON(),
        device_type: deviceType,
      }),
    })
    log('Push subscription renewed after pushsubscriptionchange')
  } catch (error) {
    console.error('Failed to renew push subscription:', error)
  }
}

self.addEventListener('pushsubscriptionchange', (event) => {
  event.waitUntil(resubscribeToPush())
})

// ============================================================
// BACKGROUND SYNC — flush the offline write queue on reconnect
// ============================================================

// Ask any live client (window) to run the authoritative Dexie queue flush
// (syncService.processOfflineQueue) so conflict detection + temp-id remapping
// stay in one place. If no client is alive (app fully closed) the flush is
// deferred to next app open, which is wired via the `online` listener.
async function notifyClientsToSync() {
  const clients = await self.clients.matchAll({ includeUncontrolled: true, type: 'window' })
  for (const client of clients) {
    client.postMessage({ type: 'SYNC_NOW' })
  }
}

self.addEventListener('sync', (event) => {
  // Workbox replays its own background-sync queue automatically via the plugin.
  if (event.tag === 'workbox-background-sync:gearcargo-sync-queue') {
    log('Background sync triggered for gearcargo-sync-queue')
  }

  // Our explicit tag: wake clients to flush the Dexie offline queue.
  if (event.tag === FLUSH_QUEUE_SYNC_TAG) {
    event.waitUntil(notifyClientsToSync())
  }
})

// ============================================================
// PERIODIC BACKGROUND SYNC — keep reminders fresh while closed
// ============================================================

// Read-only: warm the reminders endpoint so the api-cache holds a fresh copy
// for the next (possibly offline) open. No writes, no conflict surface. The
// httpOnly auth cookie is sent automatically; if the session has expired the
// fetch simply fails and we leave the previous cache untouched.
async function refreshRemindersCache() {
  try {
    const url = '/api/reminders'
    const response = await fetch(url, { credentials: 'include' })
    if (response && response.ok) {
      const cache = await caches.open('api-cache')
      await cache.put(url, response.clone())
      const clients = await self.clients.matchAll({ includeUncontrolled: true, type: 'window' })
      for (const client of clients) {
        client.postMessage({ type: 'REMINDERS_REFRESHED' })
      }
    }
  } catch (error) {
    // Offline or session expired — best-effort, keep the existing cache.
    log('Periodic reminder refresh skipped:', error)
  }
}

self.addEventListener('periodicsync', (event) => {
  if (event.tag === REMINDER_REFRESH_TAG) {
    event.waitUntil(refreshRemindersCache())
  }
})

log('GearCargo Service Worker loaded with Background Sync support')
