/* eslint-disable no-restricted-globals */

// CACHE VERSION - increment to force update
const CACHE_VERSION = 'v2.0.1'
console.log('Service Worker Version:', CACHE_VERSION)

import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching'
import { registerRoute, NavigationRoute } from 'workbox-routing'
import { CacheFirst, NetworkFirst, StaleWhileRevalidate, NetworkOnly } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'
import { BackgroundSyncPlugin } from 'workbox-background-sync'

// ============================================================
// BACKGROUND SYNC CONFIGURATION
// ============================================================

// Create a background sync plugin for API mutations (POST, PUT, DELETE)
const bgSyncPlugin = new BackgroundSyncPlugin('gearcargo-sync-queue', {
  maxRetentionTime: 24 * 60, // Retry for up to 24 hours (in minutes)
  onSync: async ({ queue }) => {
    let entry
    while ((entry = await queue.shiftRequest())) {
      try {
        const response = await fetch(entry.request.clone())
        
        // Notify the app that sync succeeded
        const clients = await self.clients.matchAll()
        for (const client of clients) {
          client.postMessage({
            type: 'SYNC_SUCCESS',
            url: entry.request.url,
            method: entry.request.method,
          })
        }
        
        console.log('Background sync successful:', entry.request.url)
      } catch (error) {
        console.error('Background sync failed, re-queuing:', error)
        // Put the entry back in the queue and re-throw to signal failure
        await queue.unshiftRequest(entry)
        throw error
      }
    }
    
    // Notify app that all syncs are complete
    const clients = await self.clients.matchAll()
    for (const client of clients) {
      client.postMessage({
        type: 'SYNC_COMPLETE',
        message: 'All offline changes have been synced',
      })
    }
  },
})

// ============================================================
// PRECACHING
// ============================================================

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST)

// Clean up old caches
cleanupOutdatedCaches()

// SPA navigation fallback - serve index.html for all navigation requests
const navigationHandler = createHandlerBoundToURL('/index.html')
const navigationRoute = new NavigationRoute(navigationHandler, {
  denylist: [/^\/api/],
})
registerRoute(navigationRoute)

// Take control of clients immediately after activation
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim())
})

// Cache Google Fonts stylesheets
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
)

// Cache Google Fonts webfonts
registerRoute(
  ({ url }) => url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
        maxEntries: 30,
      }),
    ],
  })
)

// Cache Material Icons
registerRoute(
  ({ url }) => url.href.includes('material-icons') || url.href.includes('Material+Icons'),
  new CacheFirst({
    cacheName: 'material-icons',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365,
        maxEntries: 10,
      }),
    ],
  })
)

// Cache images
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
    ],
  })
)

// Cache API GET calls with NetworkFirst strategy (for reading data)
registerRoute(
  ({ url, request }) => url.pathname.startsWith('/api/') && request.method === 'GET',
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24, // 24 hours
      }),
    ],
    networkTimeoutSeconds: 10,
  })
)

// ============================================================
// BACKGROUND SYNC FOR API MUTATIONS (POST, PUT, DELETE)
// Queue failed requests when offline and retry when back online
// ============================================================

// Handle POST requests with background sync
registerRoute(
  ({ url, request }) => url.pathname.startsWith('/api/') && request.method === 'POST',
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'POST'
)

// Handle PUT requests with background sync
registerRoute(
  ({ url, request }) => url.pathname.startsWith('/api/') && request.method === 'PUT',
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'PUT'
)

// Handle PATCH requests with background sync
registerRoute(
  ({ url, request }) => url.pathname.startsWith('/api/') && request.method === 'PATCH',
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'PATCH'
)

// Handle DELETE requests with background sync
registerRoute(
  ({ url, request }) => url.pathname.startsWith('/api/') && request.method === 'DELETE',
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'DELETE'
)

// Cache static assets
registerRoute(
  ({ request }) =>
    request.destination === 'script' ||
    request.destination === 'style',
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
  })
)

// ============================================================
// OFFLINE FALLBACK
// ============================================================
const FALLBACK_HTML_URL = '/offline.html'

// ============================================================
// MESSAGE HANDLING
// ============================================================

// Listen for messages from the main thread
self.addEventListener('message', async (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
  
  // Handle request to get pending sync count
  if (event.data && event.data.type === 'GET_PENDING_SYNC_COUNT') {
    try {
      const db = await openSyncDatabase()
      const tx = db.transaction('requests', 'readonly')
      const store = tx.objectStore('requests')
      const count = await new Promise((resolve, reject) => {
        const request = store.count()
        request.onsuccess = () => resolve(request.result)
        request.onerror = () => reject(request.error)
      })
      
      event.ports[0].postMessage({ count })
    } catch (error) {
      event.ports[0].postMessage({ count: 0, error: error.message })
    }
  }
  
  // Force sync attempt
  if (event.data && event.data.type === 'FORCE_SYNC') {
    try {
      await self.registration.sync.register('workbox-background-sync:gearcargo-sync-queue')
      event.ports[0]?.postMessage({ success: true })
    } catch (error) {
      console.error('Manual sync registration failed:', error)
      event.ports[0]?.postMessage({ success: false, error: error.message })
    }
  }
})

// Helper to open the Workbox background sync IndexedDB
function openSyncDatabase() {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open('workbox-background-sync', 3)
    request.onerror = () => reject(request.error)
    request.onsuccess = () => resolve(request.result)
  })
}

// ============================================================
// PUSH NOTIFICATIONS
// ============================================================

// Handle push notifications
self.addEventListener('push', (event) => {
  if (!event.data) return
  
  const data = event.data.json()
  
  const options = {
    body: data.body || 'New notification',
    icon: '/icons/logo-192.png',
    badge: '/icons/logo-72.png',
    vibrate: [100, 50, 100],
    data: {
      url: data.url || '/',
    },
    actions: data.actions || [],
    tag: data.tag || 'gearcargo-notification',
    renotify: true,
  }
  
  event.waitUntil(
    self.registration.showNotification(data.title || 'GearCargo', options)
  )
})

// Handle notification click
self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  
  const urlToOpen = event.notification.data?.url || '/'
  
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        // Check if there's already a window open
        for (const client of clientList) {
          if (client.url === urlToOpen && 'focus' in client) {
            return client.focus()
          }
        }
        // Open a new window
        if (self.clients.openWindow) {
          return self.clients.openWindow(urlToOpen)
        }
      })
  )
})

// ============================================================
// SYNC EVENT (Fallback for browsers that support it)
// ============================================================

self.addEventListener('sync', (event) => {
  if (event.tag === 'workbox-background-sync:gearcargo-sync-queue') {
    console.log('Background sync triggered for gearcargo-sync-queue')
  }
})

console.log('GearCargo Service Worker loaded with Background Sync support')
